---
title: "NHSRConference"
author: "Kieran Dale"
date: "26/07/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

rm(list=ls())

library(ggplot2)
library(tidyverse)
library(tidytext)
library(textdata)
library(digest)
library(wordcloud)
library(scales)
library(ggthemes)
library(lubridate)
library(splitstackshape)

```

We should synthesize the data

```{r synthesize}

# number of patients to simulate entering ED
number_of_patients <- 150000

# start and end dates
start_date <- as.POSIXct("07-07-1995 00:00:00", format = "%d-%m-%Y %H:%M:%S")
end_date <- as.POSIXct("07-07-1996 00:00:00", format = "%d-%m-%Y %H:%M:%S")

# locations within the emergency department/emergency floor
ward_names <- c("Triage",
                "Waiting Room",
                "Consultation",
                "Ward 1",
                "Ward 2",
                "Ward 3",
                "Ward 4")

# synthesize data
data <- data.frame(
  
  # unique attendance ID
  attendance_id = sapply(stats::rnorm(n = number_of_patients), digest::sha1),
  
  # equally space entries
  equally_spaced_entries = seq.POSIXt(from = start_date,
                                      to = end_date,
                                      length = number_of_patients),
  
  # these random variables will add natural "noise" to ED arrival patterns
  random_variable_long = round(abs(rnorm(n = number_of_patients,
                                    mean = 0))*60,0),
  
  random_variable_short = round(abs(rnorm(n = number_of_patients,
                                    mean = 0))*20,0)) %>% 
  
  mutate(
  
  # add "noise" to entry times
  entry_time = equally_spaced_entries + 
    lubridate::minutes(random_variable_long) - 
    lubridate::minutes(random_variable_short),
  
  # randomly assign LoS in different ED locations
  time_in_triage = abs(rnorm(number_of_patients,
                             10,
                             3)),
  time_in_waiting_room = rnorm(number_of_patients,120,60),
  time_in_waiting_room = ifelse(time_in_waiting_room<0, 0, time_in_waiting_room),
  time_in_consultation = rnorm(number_of_patients,70,20),
  time_in_consultation = ifelse(time_in_consultation<0, 0, time_in_consultation),
  time_in_ward = rnorm(number_of_patients,50,20),
  time_in_ward = ifelse(time_in_ward<0, 0, time_in_ward),
  
  # randomly assign where patients go after consultation
  ward_name = sample(c("Ward 1", "Ward 2", "Ward 3", "Ward 4", "Went Home"),number_of_patients, replace = TRUE, prob = c(0.25,0.1,0.05,0.025, 0.575)),
  
  # calculate exit time from ED
  exit_time_ED = entry_time + 
    lubridate::minutes(round(time_in_triage)) + 
    lubridate::minutes(round(time_in_waiting_room)) + 
    lubridate::minutes(round(time_in_consultation)),
  
  # calculate exit time from ward
  exit_time_ward = ifelse(ward_name == "Went Home", 
                          exit_time_ED, 
                          exit_time_ED + lubridate::minutes(round(time_in_ward)))
  
  )
  
  



# append the same data to simulate entries in "busy periods" of the day i.e. 6-9am, 6pm-10pm
busy_period <- data %>%

  filter((lubridate::hour(entry_time) %in% c(7,8,9)|
         lubridate::hour(exit_time_ED)  %in% c(6,7,8))|
           (lubridate::hour(entry_time) %in% c(19,20,21,22)|
         lubridate::hour(exit_time_ED)  %in% c(18,19,20,21)))

n_patients_busy <- nrow(busy_period)
    
busy_period$random_variable_long = round((rnorm(n = n_patients_busy,mean = 0))*10,0)
busy_period$random_variable_short = round((rnorm(n = n_patients_busy,mean = 0))*4,0)

busy_period <- busy_period %>% 
  
  mutate(
    entry_time = entry_time + lubridate::minutes(random_variable_long) + lubridate::minutes(random_variable_short),
    
    time_in_waiting_room = rnorm(n_patients_busy,200,40),
    time_in_waiting_room = ifelse(time_in_waiting_room<0, 0, time_in_waiting_room),
    time_in_consultation = rnorm(n_patients_busy,50,20),
    time_in_consultation = ifelse(time_in_consultation<0, 0, time_in_consultation),
    time_in_ward = rnorm(n_patients_busy,80,20),
    time_in_ward = ifelse(time_in_ward<0, 0, time_in_ward),

    exit_time_ED = entry_time + 
      lubridate::minutes(round(time_in_triage)) + 
      lubridate::minutes(round(time_in_waiting_room)) + 
      lubridate::minutes(round(time_in_consultation)),
  
    exit_time_ward = ifelse(ward_name == "Went Home", 
                            exit_time_ED, 
                            exit_time_ED + lubridate::minutes(round(time_in_ward)))
    
  )


df <- rbind(data,
            busy_period) %>% 
  
  # calculate LoS in ED
  mutate(ED_LOS = time_in_triage + time_in_waiting_room + time_in_consultation)


```



```{r plots}

df2 <- df[df$ED_LOS < 720 & df$ED_LOS > 0, ]
df2$EDTimeGroup <- cut(
  df$ED_LOS,
  seq(0, 720, 10),
  labels = seq(1/6, 12, 1/6)
)

df_all <- df2 %>%
  group_by(EDTimeGroup) %>%
  summarise(Activity = n())

HockeyTotal <- ggplot(df_all, aes(x = EDTimeGroup, y = Activity)) +
  geom_bar(stat = "sum",fill= "#23203F") +
  theme_classic() +
  theme(legend.position = "none")+
  scale_x_discrete(breaks=seq(0, 12, 1))+
  xlab("Hours in ED") +
  ylab("Total attendances (2016-2019)")+
  geom_vline(xintercept=24.5,linetype="dashed",colour="red",size=2)

HockeyTotal

ggsave("HockeyTotal.png", plot = last_plot(), height = 10, width = 10)

```


```{r plots}

df2 <- df

df2$Date <- lubridate::date(df2$entry_time)
df2$Hour <- lubridate::hour(df2$entry_time)
df2$Weekday <- weekdays(df2$entry_time)

HourlyActivity <- df2 %>%
  group_by(Date, Hour) %>%
  summarise(Arrivals = n())


WeeklyPattern <- df2 %>%
  group_by(Weekday, Hour) %>%
  summarise(Arrivals = n()) %>% 
  tidyr::drop_na(Weekday)

WeeklyPattern$Weekday <- factor(WeeklyPattern$Weekday,levels = c("Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"))

WeeklyPattern$HourLab <- ifelse(WeeklyPattern$Hour == 0, "Midnight",
                                ifelse(WeeklyPattern$Hour < 12, paste0(WeeklyPattern$Hour,"am"),
                                       ifelse(WeeklyPattern$Hour == 12, "Noon",
                                              paste0(WeeklyPattern$Hour-12,"pm")
                                              )))

WeeklyPattern$HourLab <- factor(WeeklyPattern$HourLab,levels = c("1am","2am","3am","4am","5am","6am","7am","8am","9am","10am","11am","Noon",
                                                                 "1pm","2pm","3pm","4pm","5pm","6pm","7pm","8pm","9pm","10pm","11pm","Midnight"))


WeeklyDemand <- ggplot(WeeklyPattern,aes(Weekday,HourLab,fill=Arrivals)) +
  geom_tile()+
  scale_fill_distiller(palette = "RdYlGn") +
  ylab("Time of day")+
  ggthemes::theme_economist_white(gray_bg = F) + 
  theme(legend.position = "none", 
        axis.title = element_blank())


WeeklyDemand

ggsave("WeeklyDemand.png", plot = last_plot(), height = 10, width = 10)

```




```{r}

df3 <- 
df2 %>% 
    slice(1:30) %>% 
    mutate(triage_start = entry_time,
           triage_end = entry_time + lubridate::minutes(round(time_in_triage)),
           wr_start = triage_end,
           wr_end = wr_start + lubridate::minutes(round(time_in_waiting_room)),
           consult_start = wr_end,
           consult_end = consult_start + lubridate::minutes(round(time_in_consultation)),
           ward_start = consult_end,
           ward_end = ward_start + lubridate::minutes(round(time_in_ward))) %>%
  arrange(triage_start) %>% 
  mutate(pt = n():1)

Pt_Journey <- 
ggplot(df3) +
  geom_rect(aes(xmin = triage_start,
                xmax = triage_end,
                ymin = pt-0.3,
                ymax = pt+0.3,
                fill = "Triage")) +
  geom_rect(aes(xmin = wr_start,
                xmax = wr_end,
                ymin = pt-0.3,
                ymax = pt+0.3,
                fill = "Waiting Room")) +
  geom_rect(aes(xmin = consult_start,
                xmax = consult_end,
                ymin = pt-0.3,
                ymax = pt+0.3,
                fill = "Consultation")) +
  geom_rect(aes(xmin = ward_start,
                xmax = ward_end,
                ymin = pt-0.3,
                ymax = pt+0.3,
                fill = "Ward")) +
  theme_bw() +
  ggtitle("Patient Journeys in ED") +
  scale_fill_manual(breaks=c("Triage",
                             "Waiting Room",
                             "Consultation",
                             "Ward"),
                    values = c("pink",
                               "slate blue",
                               "purple4",
                               "light blue"),
                    name = "")+
scale_x_datetime(breaks = seq(floor_date(df3$triage_start[1], unit = "hours"),
                              ceiling_date(df3$ward_end[nrow(df3)]+lubridate::hours(3), unit = "hours"), 
                              "3 hours"),
                 labels = date_format("%b %d\n%H:%M", tz = "GMT"))+
theme(axis.text.y = element_blank(),
      axis.text.x = element_text(angle = 0, vjust=0, hjust=0.5))


Pt_Journey

ggsave("Pt_Journey.png", Pt_Journey, height = 6, width = 10)

```






```{r plots}

df4 <- df[df$ED_LOS < 720 & df$ED_LOS > 0, ]

df_hist <- df4 %>%
  select(time_in_triage,
         time_in_waiting_room,
         time_in_consultation,
         time_in_ward) %>% 
  rename("Triage" = 1,
         "Waiting Room" = 2,
         "Consultation" = 3,
         "Ward" = 4) %>% 
  pivot_longer(cols = 1:4, names_to = "Location", values_to = "LOS") %>% 
  mutate(Location = factor(Location, levels = c("Triage",
                                                "Waiting Room",
                                                "Consultation",
                                                "Ward")))

df_mean <- df_hist %>% 
  group_by(Location) %>% 
  summarise(LOS = mean(LOS, na.rm = T))

LOS_Plot <- ggplot(df_hist) +
  geom_histogram(aes(x = LOS/60),
                 stat = "bin",
                 fill= "#23203F", 
                 bins = 50) +
  theme_bw() +
  theme(legend.position = "none")+
  xlab("Hours spent") +
  ylab("Total patients")+
  facet_wrap(~Location, scales = "free_y", nrow = 1)

LOS_Plot

ggsave("LOS_Plot.png", LOS_Plot, height = 4, width = 12)

```





```{r}

df_ma <- df2 %>% 
  filter(ward_name != "Went Home") %>% 
    mutate(triage_start = entry_time,
           triage_end = entry_time + lubridate::minutes(round(time_in_triage)),
           wr_start = triage_end,
           wr_end = wr_start + lubridate::minutes(round(time_in_waiting_room)),
           consult_start = wr_end,
           consult_end = consult_start + lubridate::minutes(round(time_in_consultation)),
           ward_start = consult_end,
           ward_end = ward_start + lubridate::minutes(round(time_in_ward))) %>%
  mutate(ward_start_round = lubridate::floor_date(ward_start, unit = "30 minutes"),
         ward_end_round = lubridate::floor_date(ward_end, unit = "30 minutes")) %>% 
  select(ward_name,
         ward_start_round,
         ward_end_round) %>% 
  drop_na(ward_start_round,
          ward_end_round) %>% 
  rename("ward" = 1,
         "start" = 2,
         "end" = 3)



# this is the most simple solution
block_duration <- 15 # minutes

plot_ma <- data.frame(
  times = seq.POSIXt(from = min(df_ma$start),
                     to = max(df_ma$end),
                     by = paste0(block_duration, " min"))
)

int_diff_vec <- int_diff(plot_ma$times)

# repeat rows for half hour blocks
ma_data <- df_ma %>% 
  
  mutate(time_blocks = as.numeric(difftime(end, start, units = "mins"))/block_duration) %>% 
  
  select(-end) %>% 
  
  mutate(rep_times = ifelse(time_blocks == 0, 1, time_blocks - 1),
         
         row_num = 1:n()) 


# split into blocks
ma_data <- splitstackshape::expandRows(data.table::as.data.table(ma_data), "rep_times")

# turn back into dataframe
ma_data <- as.data.frame(ma_data) %>% 
  
  group_by(row_num) %>% 
  
  mutate(blocks_to_add = 1:n() - 1,
         
         time_counts = start + lubridate::minutes(block_duration*blocks_to_add)) %>% 
  
  ungroup()


plot_ma$`Ward 1` <- 0
plot_ma$`Ward 2` <- 0
plot_ma$`Ward 3` <- 0
plot_ma$`Ward 4` <- 0


for (ii in 1:length(int_diff_vec)) {
  
  number_present_w1 <- sum(ma_data$time_counts[ma_data$ward == "Ward 1"] %within% int_diff_vec[ii])
  number_present_w2 <- sum(ma_data$time_counts[ma_data$ward == "Ward 2"] %within% int_diff_vec[ii])
  number_present_w3 <- sum(ma_data$time_counts[ma_data$ward == "Ward 3"] %within% int_diff_vec[ii])
  number_present_w4 <- sum(ma_data$time_counts[ma_data$ward == "Ward 4"] %within% int_diff_vec[ii])
  
  plot_ma$`Ward 1`[ii] <- number_present_w1
  plot_ma$`Ward 2`[ii] <- number_present_w2
  plot_ma$`Ward 3`[ii] <- number_present_w3
  plot_ma$`Ward 4`[ii] <- number_present_w4
  
}

```

```{r plotma}


ggplot(plot_ma %>% 
         select(times,
                `Ward 1`,
                `Ward 2`,
                `Ward 3`,
                `Ward 4`) %>% 
         pivot_longer(cols = 2:5,
                      names_to = "Ward",
                      values_to = "count"), 
       aes(x = times, y = count))+
  geom_line(size = 1, alpha = 0.3, colour = "#23203F")+
  tidyquant::geom_ma(n = 96*7, size = 1.5)+
  facet_wrap(~Ward) +
  theme_bw() +
  theme(legend.position = "none")+
  xlab("Date") +
  ylab("Bays/Beds Occupied")+
  ggtitle("Ward Occupancy Over Time")


ggsave("Ward_Occupancy_Over_Time.png", plot = last_plot(), height = 8, width = 10)

```





```{r plotma}


ggplot(plot_ma %>% 
         filter(month(times) == 7 & year(times) == 1995 & day(times) %in% seq(7,9,1)) %>% 
         select(times,
                `Ward 1`,
                `Ward 2`,
                `Ward 3`,
                `Ward 4`) %>% 
         pivot_longer(cols = 2:5,
                      names_to = "Ward",
                      values_to = "count"), 
       aes(x = times, y = count))+
  geom_line(size = 1, alpha = 0.7, colour = "#23203F")+
  facet_wrap(~Ward) +
  theme_bw() +
  theme(legend.position = "none")+
  xlab("Date") +
  ylab("Bays/Beds Occupied")+
  ggtitle("Ward Occupancy Over A 3-Day Window")+
  scale_x_datetime(labels = date_format("%b %d", tz = "GMT"))


ggsave("Ward_Occupancy_Over_Time_Zoomed.png", plot = last_plot(), height = 8, width = 10)

```



```{r}

# Total Entry Exit Times
df_ma <- df %>% 
    mutate(triage_start = entry_time,
           triage_end = entry_time + lubridate::minutes(round(time_in_triage)),
           wr_start = triage_end,
           wr_end = wr_start + lubridate::minutes(round(time_in_waiting_room)),
           consult_start = wr_end,
           consult_end = consult_start + lubridate::minutes(round(time_in_consultation)),
           ward_start = consult_end,
           ward_end = ward_start + lubridate::minutes(round(time_in_ward))) %>%
  mutate(ward_start = lubridate::floor_date(ward_start, unit = "30 minutes"),
         ward_end = lubridate::floor_date(ward_end, unit = "30 minutes"),
         wr_start = lubridate::floor_date(wr_start, unit = "30 minutes"),
         wr_end = lubridate::floor_date(wr_end, unit = "30 minutes"),
         triage_start = lubridate::floor_date(triage_start, unit = "30 minutes"),
         triage_end = lubridate::floor_date(triage_end, unit = "30 minutes"),
         consult_start = lubridate::floor_date(consult_start, unit = "30 minutes"),
         consult_end = lubridate::floor_date(consult_end, unit = "30 minutes")) %>% 
  select(ward_name,
         ward_start,
         ward_end,
         wr_start,
         wr_end,
         triage_start,
         triage_end,
         consult_start,
         consult_end) %>% 
  drop_na(ward_start,
         ward_end,
         wr_start,
         wr_end,
         triage_start,
         triage_end,
         consult_start,
         consult_end) %>% 
  rename("ward" = 1)


# this is the most simple solution
block_duration <- 15 # minutes

plot_ma <- data.frame(
  times = seq.POSIXt(from = min(df_ma$triage_start),
                     to = max(df_ma$ward_end),
                     by = paste0(block_duration, " min"))
)

int_diff_vec <- int_diff(plot_ma$times)

# repeat rows for half hour blocks

# transform table
ward <- df_ma %>% select(ward_start, ward_end) %>% rename("start" = 1, "end" = 2) %>% mutate(Location = "Ward")
consultation <- df_ma %>% select(consult_start, consult_end) %>% rename("start" = 1, "end" = 2) %>% mutate(Location = "Consultation")
triage <- df_ma %>% select(triage_start, triage_end) %>% rename("start" = 1, "end" = 2) %>% mutate(Location = "Triage")
wr <- df_ma %>% select(wr_start, wr_end) %>% rename("start" = 1, "end" = 2) %>% mutate(Location = "Waiting Room")

df_ma_transform <- rbind(
  ward,
  consultation,
  triage,
  wr
)
  
ma_data <- df_ma_transform %>% 
  
  mutate(time_blocks = as.numeric(difftime(end, start, units = "mins"))/block_duration) %>% 
  
  select(-end) %>% 
  
  mutate(rep_times = ifelse(time_blocks == 0, 1, time_blocks - 1),
         
         row_num = 1:n()) 


# split into blocks
ma_data <- splitstackshape::expandRows(data.table::as.data.table(ma_data), "rep_times")

print(object.size(ma_data), units = "Gb")

# turn back into dataframe
ma_data <- as.data.frame(ma_data) %>% 
  
  group_by(row_num) %>% 
  
  mutate(blocks_to_add = 1:n() - 1,
         
         time_counts = start + lubridate::minutes(block_duration*blocks_to_add)) %>% 
  
  ungroup() %>% 
  
  tidyr::drop_na(time_counts)


plot_ma$`Ward` <- 0
plot_ma$`Waiting Room` <- 0
plot_ma$`Consultation` <- 0
plot_ma$`Triage` <- 0


for (ii in 1:length(int_diff_vec)) {

  
  number_present_1 <- sum(ma_data$time_counts[ma_data$Location == "Ward"] %within% int_diff_vec[ii], na.rm = T)
  number_present_2 <- sum(ma_data$time_counts[ma_data$Location == "Consultation"] %within% int_diff_vec[ii], na.rm = T)
  number_present_3 <- sum(ma_data$time_counts[ma_data$Location == "Triage"] %within% int_diff_vec[ii], na.rm = T)
  number_present_4 <- sum(ma_data$time_counts[ma_data$Location == "Waiting Room"] %within% int_diff_vec[ii], na.rm = T)
  
  plot_ma$`Ward`[ii] <- number_present_1
  plot_ma$`Consultation`[ii] <- number_present_2
  plot_ma$`Triage`[ii] <- number_present_3
  plot_ma$`Waiting Room`[ii] <- number_present_4
  
}



```



```{r}

# Plots

# This chunk of code will print our a bar chart of hourly activity
occupancy <- plot_ma %>% 
  
  pivot_longer(cols = 2:5, names_to = "location", values_to = "pts") %>% 
  
  mutate(hour_num = lubridate::hour(lubridate::floor_date(times, unit = "hours")),
         single_day = floor_date(times, unit = "days")) %>% 
  
  dplyr::group_by(location, single_day, hour_num) %>% 
  
  summarise(pts = mean(pts, na.rm = T)) %>% 
  
  pivot_wider(values_from = "pts", names_from = "hour_num") %>% 
  
  select(location,
         single_day,
         `1`,
         `2`,
         `3`,
         `4`,
         `5`,
         `6`,
         `7`,
         `8`,
         `9`,
         `10`,
         `11`,
         `12`,
         `13`,
         `14`,
         `15`,
         `16`,
         `17`,
         `18`,
         `19`,
         `20`,
         `21`,
         `22`,
         `23`,
         `0`) %>% 
  
  ungroup()


rename_cols <-  c(
  "location",
  "single_day",
  "1am","2am","3am","4am","5am","6am","7am","8am","9am","10am","11am","Noon",
  "1pm","2pm","3pm","4pm","5pm","6pm","7pm","8pm","9pm","10pm","11pm","Midnight"
                  )
  

colnames(occupancy) <- rename_cols

utilisation_median <- occupancy %>%
  group_by(location) %>%
  dplyr::summarise_at(vars(`1am`:`Midnight`), median, na.rm = T) %>%
  mutate(type = "Median")

utilisation_75 <-
  occupancy %>% 
    group_by(location) %>%
  dplyr::summarise_at(vars(`1am`:`Midnight`), quantile, 0.75, na.rm = T) %>% 
  mutate(type = "75th %'ile")

utilisation_85 <-
  occupancy %>% 
    group_by(location) %>%
  dplyr::summarise_at(vars(`1am`:`Midnight`), quantile, 0.85, na.rm = T) %>% 
  mutate(type = "85th %'ile")

utilisation_95 <-
  occupancy %>% 
    group_by(location) %>%
  dplyr::summarise_at(vars(`1am`:`Midnight`), quantile, 0.95, na.rm = T) %>% 
  mutate(type = "95th %'ile")

utilisation <- rbind(utilisation_median,
                     utilisation_75,
                     utilisation_85,
                     utilisation_95)

plot_data <- pivot_longer(utilisation, 2:25, names_to = "time")

plot_data$time <- factor(plot_data$time,levels = c("1am","2am","3am","4am","5am","6am","7am","8am","9am","10am","11am","Noon",
                                         "1pm","2pm","3pm","4pm","5pm","6pm","7pm","8pm","9pm","10pm","11pm","Midnight"))

plot_data$type <- factor(plot_data$type, levels = c("Median", "75th %'ile", "85th %'ile", "95th %'ile"))

plot_data$location <- factor(plot_data$location, levels = rev(c("Triage", "Waiting Room", "Consultation", "Ward")))


```



```{r}


ggplot(plot_data %>% 
         filter(type %in% c("Median", "95th %'ile")))+
  
  geom_bar(aes(x = time, y = value, fill = location), position = "stack", stat = "identity") + 
  
  facet_wrap(~type)+
  
  theme_bw() +
  xlab("") +
  ylab("Bays/Beds Occupied")+
  ggtitle("Occupancy within sections of the ED")+
  scale_fill_manual(name="", values=c("#C18DBE","#23203F","#56BABF","#F28F64","khaki1","coral1"))


ggsave("Occupancy.png", plot = last_plot(), height = 7, width = 16)


```

